# Generated by Django 3.1 on 2020-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FD_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='applicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], default=(('Yes', 'Yes'), ('No', 'No')), max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='coapplicatincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='credithistory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='graduatededucation',
            field=models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='loanamt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='loanterm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='selfemployed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='firstname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='approvals',
            name='lastname',
            field=models.CharField(default='', max_length=15),
        ),
    ]
