# Generated by Django 3.1 on 2020-08-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FD_API', '0002_auto_20200819_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='applicantincome',
            new_name='ApplicantIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='coapplicatincome',
            new_name='CoapplicatIncome',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='credithistory',
            new_name='Credit_History',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='dependants',
            new_name='Dependents',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='graduatededucation',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanamt',
            new_name='LoanAmount',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='loanterm',
            new_name='Loan_Amount_Term',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='married',
            new_name='Married',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='area',
            new_name='Property_Area',
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='selfemployed',
            new_name='Self_Employed',
        ),
    ]
